export const ADD_TODO = 'ADD_TODO'
export const UPDATE_TITLE = 'UPDATE_TITLE'
export const REMOVE_TODO = 'REMOVE_TODO'
export const COMPLETE_TODO = 'COMPLETE_TODO'
export const FETCH_TODOS = 'FETCH_TODOS'
export const SHOW_LOADER = 'SHOW_LOADER'